// ============================================================================
// Recommendations Feature — Types
// ============================================================================
//
// Shapes shared by the browser-side behaviour tracker, the live scoring API and
// the taste panel. Everything here is client-safe (no server imports).
//
// Data flow
// ---------
//   BehaviourEvent[] (localStorage)  →  TasteProfile (pure, in-browser)
//   TasteProfile  →  POST /api/recommendations  →  LiveRecommendationsResult
//   TasteProfile  →  POST /api/recommendations/explanation  →  TasteExplanation
//
// Spare-parts signals
// -------------------
//   vehicle    → which car the part fits ("Toyota Corolla")  — strongest signal
//   part type  → what the part is ("Brake Pads")
//   condition  → listing_condition (oem / aftermarket / used / refurbished)
//   budget     → hard from a price filter, soft from viewed prices

import type { ListingRecord } from "@/lib/features/listings";

// -- Behaviour events -----------------------------------------------------------

/** Listing snapshot captured at the moment of a view. */
export type ListingSignal = {
	listingId: string;
	title: string;
	/** Canonical vehicle the part fits, e.g. "Toyota Corolla". */
	vehicle: string | null;
	/** Canonical part type, e.g. "Brake Pads". */
	partType: string | null;
	price: number;
	/** `listings.listing_condition` (oem / aftermarket / used / refurbished). */
	condition: string | null;
};

/** A single thing the shopper did. Newest events weigh the most. */
export type BehaviourEvent =
	| ({ type: "view"; at: number } & ListingSignal)
	| ({ type: "favorite"; at: number } & ListingSignal)
	| {
			type: "filter";
			at: number;
			vehicle: string | null;
			partType: string | null;
			priceMin: number | null;
			priceMax: number | null;
			query: string | null;
	  };

// -- Taste profile ----------------------------------------------------------------

/** A weighted preference — `share` is the key's fraction of the total weight. */
export type WeightedPreference = { key: string; share: number };

export type BudgetSource = "filter" | "views";

/** Price preference: hard range from an explicit filter, soft band from views. */
export type TasteBudget = {
	min: number | null;
	max: number | null;
	/** Price the shopper gravitates towards — scoring peaks here. */
	target: number | null;
	source: BudgetSource | null;
};

/** Compact, bounded summary of recent behaviour — sent to the scoring API. */
export type TasteProfile = {
	eventCount: number;
	/** Keys are canonical vehicle names (e.g. "Toyota Corolla"). */
	vehicles: WeightedPreference[];
	/** Keys are canonical part types (e.g. "Brake Pads"). */
	partTypes: WeightedPreference[];
	/** Keys are `listing_condition` values. */
	conditions: WeightedPreference[];
	budget: TasteBudget;
	/** Recently viewed listing ids, newest first — excluded from results. */
	viewedIds: string[];
	/** Human label for the most recent event (shown in the taste panel). */
	lastEventLabel: string | null;
};

// -- Live recommendations -----------------------------------------------------------

/** Which signal dominated the ranking — surfaced as the engine's "decision". */
export type RecommendationStrategy = "cold-start" | "vehicle-led" | "budget-led" | "part-led" | "blended";

export type RecommendedListing = ListingRecord & {
	recommendation: { score: number; reasons: string[] };
};

export type LiveRecommendationsResult = {
	strategy: RecommendationStrategy;
	listings: RecommendedListing[];
	/** Server-side decision time in ms (scoring + DB), shown in the panel. */
	decisionMs: number;
};

// -- AI explanation -------------------------------------------------------------------

export type TasteExplanation = {
	/** One short sentence describing what the shopper seems to want. */
	text: string;
	/** `ai` = generated by the explanation model; `rules` = deterministic fallback. */
	source: "ai" | "rules";
	model: string | null;
};
